2020-09-30 16:23:32,663 ERROR 60251 nodejs.ClusterClientNoResponseError: client no response in 350197ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 60251
hostname: lxddeMacBook-Pro.local

2020-09-30 17:04:07,157 ERROR 91925 [-/192.168.7.50/-/6ms GET /gannt/created] nodejs.ReferenceError: params is not defined
    at GanntController.created (/Users/lxd/Desktop/egg-example/app/controller/gannt.js:49:46)
    at Object.callFn (/Users/lxd/Desktop/egg-example/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/lxd/Desktop/egg-example/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/lxd/Desktop/egg-example/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/lxd/Desktop/egg-example/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/lxd/Desktop/egg-example/node_modules/koa-compose/index.js:44:32)
    at next (/Users/lxd/Desktop/egg-example/node_modules/koa-compose/index.js:45:18)
    at /Users/lxd/Desktop/egg-example/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/lxd/Desktop/egg-example/node_modules/koa-compose/index.js:44:32)
    at /Users/lxd/Desktop/egg-example/node_modules/koa-compose/index.js:36:12

pid: 91925
hostname: lxddeMacBook-Pro.local

2020-09-30 17:04:58,542 ERROR 91972 [-/192.168.7.50/-/12ms GET /gannt/created] nodejs.SequelizeDatabaseError: Field 'label' doesn't have a default value
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"sqlState":"HY000","sqlMessage":"Field 'label' doesn't have a default value","sql":"INSERT INTO `gannt` (`id`) VALUES (DEFAULT);"}
original: {"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"sqlState":"HY000","sqlMessage":"Field 'label' doesn't have a default value","sql":"INSERT INTO `gannt` (`id`) VALUES (DEFAULT);"}
sql: "INSERT INTO `gannt` (`id`) VALUES (DEFAULT);"
parameters: undefined
pid: 91972
hostname: lxddeMacBook-Pro.local

2020-09-30 17:07:30,511 ERROR 92123 [-/192.168.7.50/-/17ms POST /gannt/created] nodejs.SequelizeDatabaseError: Field 'label' doesn't have a default value
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"sqlState":"HY000","sqlMessage":"Field 'label' doesn't have a default value","sql":"INSERT INTO `gannt` (`id`) VALUES (DEFAULT);"}
original: {"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"sqlState":"HY000","sqlMessage":"Field 'label' doesn't have a default value","sql":"INSERT INTO `gannt` (`id`) VALUES (DEFAULT);"}
sql: "INSERT INTO `gannt` (`id`) VALUES (DEFAULT);"
parameters: undefined
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92123
hostname: lxddeMacBook-Pro.local

2020-09-30 17:08:04,973 ERROR 92123 [-/192.168.7.50/-/5ms POST /gannt/created] nodejs.SequelizeDatabaseError: Field 'label' doesn't have a default value
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"sqlState":"HY000","sqlMessage":"Field 'label' doesn't have a default value","sql":"INSERT INTO `gannt` (`id`) VALUES (DEFAULT);"}
original: {"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"sqlState":"HY000","sqlMessage":"Field 'label' doesn't have a default value","sql":"INSERT INTO `gannt` (`id`) VALUES (DEFAULT);"}
sql: "INSERT INTO `gannt` (`id`) VALUES (DEFAULT);"
parameters: undefined
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92123
hostname: lxddeMacBook-Pro.local

2020-09-30 17:08:40,126 ERROR 92123 [-/192.168.7.50/-/5ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect integer value: '' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["asdf","","",null,1,10,"","",""]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["asdf","","",null,1,10,"","",""]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);"
parameters: ["asdf","","",null,1,10,"","",""]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92123
hostname: lxddeMacBook-Pro.local

2020-09-30 17:09:45,844 ERROR 92123 [-/192.168.7.50/-/5ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect integer value: '' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["asdf","","",null,1,10,"","",""]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["asdf","","",null,1,10,"","",""]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);"
parameters: ["asdf","","",null,1,10,"","",""]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92123
hostname: lxddeMacBook-Pro.local

2020-09-30 17:10:06,242 ERROR 92219 [-/192.168.7.50/-/17ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect integer value: '' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["111","","",null,1,10,"","",""]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["111","","",null,1,10,"","",""]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);"
parameters: ["111","","",null,1,10,"","",""]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 17:11:20,846 ERROR 92219 [-/192.168.7.50/-/8ms POST /gannt/created] nodejs.SequelizeDatabaseError: Out of range value for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_WARN_DATA_OUT_OF_RANGE","errno":1264,"sqlState":"22003","sqlMessage":"Out of range value for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["1","1",1601136000000,1601222400000,1,10,"","1","1"]}
original: {"code":"ER_WARN_DATA_OUT_OF_RANGE","errno":1264,"sqlState":"22003","sqlMessage":"Out of range value for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["1","1",1601136000000,1601222400000,1,10,"","1","1"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);"
parameters: ["1","1",1601136000000,1601222400000,1,10,"","1","1"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 17:15:48,693 ERROR 92219 [-/192.168.7.50/-/3ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect integer value: '' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["asdf","asdf","",null,null,10,"","a","a"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);","parameters":["asdf","asdf","",null,null,10,"","a","a"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);"
parameters: ["asdf","asdf","",null,null,10,"","a","a"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 17:30:17,280 ERROR 92219 [-/192.168.7.50/-/8ms POST /gannt/created] nodejs.SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:218:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeUniqueConstraintError"
errors: [{"message":"gannt.PRIMARY must be unique","type":"unique violation","path":"gannt.PRIMARY","value":"3","origin":"DB","instance":{"id":3,"label":"需求2","user":"John Doe","start":-120,"endDate":"2020-07-21","duration":1209600000,"percent":85,"type":"milestone","proType":"产品需求","risk":"风险预警xxx"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}]
fields: {"gannt.PRIMARY":"3"}
parent: {"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'gannt.PRIMARY'","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",-120,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'gannt.PRIMARY'","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",-120,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 17:43:40,832 ERROR 92219 [-/192.168.7.50/-/5ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect datetime value: '-120' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '-120' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",-120,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '-120' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",-120,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
parameters: [3,"需求2","John Doe",-120,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 17:44:52,617 ERROR 92219 [-/192.168.7.50/-/5ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect datetime value: '1209600000' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1209600000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1209600000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1209600000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1209600000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
parameters: [3,"需求2","John Doe",1209600000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 17:45:25,425 ERROR 92219 [-/192.168.7.50/-/5ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect datetime value: '1601222400000' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1601222400000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1601222400000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1601222400000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1601222400000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
parameters: [3,"需求2","John Doe",1601222400000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 17:45:45,943 ERROR 92219 [-/192.168.7.50/-/2ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect datetime value: '1601222400000' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1601222400000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1601222400000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1601222400000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1601222400000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
parameters: [3,"需求2","John Doe",1601222400000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 17:46:38,743 ERROR 92219 [-/192.168.7.50/-/3ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect datetime value: '1601222400000' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1601222400000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe","1601222400000","2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1601222400000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe","1601222400000","2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
parameters: [3,"需求2","John Doe","1601222400000","2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 17:48:04,994 ERROR 92219 [-/192.168.7.50/-/2ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect datetime value: '1601222400' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1601222400' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1601222400,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1601222400' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1601222400,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
parameters: [3,"需求2","John Doe",1601222400,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 18:05:33,981 ERROR 92219 [-/192.168.7.50/-/2ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect datetime value: '1599494400000' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1599494400000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1599494400000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1599494400000' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe",1599494400000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
parameters: [3,"需求2","John Doe",1599494400000,"2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 92219
hostname: lxddeMacBook-Pro.local

2020-09-30 18:13:46,687 ERROR 94111 [-/192.168.7.50/-/26ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect datetime value: '' for column 'start' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe","","2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '' for column 'start' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe","","2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
parameters: [3,"需求2","John Doe","","2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 94111
hostname: lxddeMacBook-Pro.local

2020-09-30 18:14:00,281 ERROR 94111 [-/192.168.7.50/-/10ms POST /gannt/created] nodejs.SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:218:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeUniqueConstraintError"
errors: [{"message":"gannt.PRIMARY must be unique","type":"unique violation","path":"gannt.PRIMARY","value":"3","origin":"DB","instance":{"id":3,"label":"需求2","user":"John Doe","start":"2020-09-20 00-00-00","endDate":"2020-07-21","duration":1209600000,"percent":85,"type":"milestone","proType":"产品需求","risk":"风险预警xxx"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}]
fields: {"gannt.PRIMARY":"3"}
parent: {"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'gannt.PRIMARY'","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe","2020-09-20 00-00-00","2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
original: {"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry '3' for key 'gannt.PRIMARY'","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":[3,"需求2","John Doe","2020-09-20 00-00-00","2020-07-21",1209600000,85,"milestone","产品需求","风险预警xxx"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 94111
hostname: lxddeMacBook-Pro.local

2020-09-30 18:32:28,848 ERROR 94111 [-/192.168.7.50/-/4ms POST /gannt/created] nodejs.SequelizeDatabaseError: Incorrect datetime value: '1600099200000' for column 'endDate' at row 1
    at Query.formatError (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1600099200000' for column 'endDate' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":["1","直播","allan","2020-09-01 00-00-00",1600099200000,null,10,"","紧急","无"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE","errno":1292,"sqlState":"22007","sqlMessage":"Incorrect datetime value: '1600099200000' for column 'endDate' at row 1","sql":"INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);","parameters":["1","直播","allan","2020-09-01 00-00-00",1600099200000,null,10,"","紧急","无"]}
sql: "INSERT INTO `gannt` (`id`,`label`,`user`,`start`,`endDate`,`duration`,`percent`,`type`,`proType`,`risk`) VALUES (?,?,?,?,?,?,?,?,?,?);"
parameters: ["1","直播","allan","2020-09-01 00-00-00",1600099200000,null,10,"","紧急","无"]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 94111
hostname: lxddeMacBook-Pro.local

2020-09-30 20:16:51,002 ERROR 60251 nodejs.ClusterClientNoResponseError: client no response in 4527570ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 60251
hostname: lxddeMacBook-Pro.local

2020-10-01 08:42:57,837 ERROR 60251 nodejs.ClusterClientNoResponseError: client no response in 44706812ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 60251
hostname: lxddeMacBook-Pro.local

2020-10-01 10:04:42,967 ERROR 96469 nodejs.ClusterClientNoResponseError: client no response in 574005ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 96469
hostname: localhost

2020-10-01 10:14:57,921 ERROR 96469 nodejs.ClusterClientNoResponseError: client no response in 574935ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 96469
hostname: localhost

2020-10-01 10:24:52,962 ERROR 96469 nodejs.ClusterClientNoResponseError: client no response in 575030ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 96469
hostname: localhost

2020-10-01 10:45:24,015 ERROR 96469 nodejs.ClusterClientNoResponseError: client no response in 575015ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 96469
hostname: localhost

2020-10-01 10:55:19,026 ERROR 96469 nodejs.ClusterClientNoResponseError: client no response in 574995ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 96469
hostname: localhost

2020-10-01 11:05:34,066 ERROR 96469 nodejs.ClusterClientNoResponseError: client no response in 575026ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 96469
hostname: localhost

2020-10-01 11:15:31,002 ERROR 96469 nodejs.ClusterClientNoResponseError: client no response in 576927ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 96469
hostname: localhost

2020-10-01 11:25:46,058 ERROR 96469 nodejs.ClusterClientNoResponseError: client no response in 575039ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 96469
hostname: localhost

